# Generated by Django 2.1.7 on 2019-03-30 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyBeeUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='프로필 사진')),
                ('introduce', models.TextField(blank=True, max_length=100, null=True, verbose_name='소개')),
                ('total_like', models.IntegerField(default=0, verbose_name='총 좋아요 수')),
                ('total_down', models.IntegerField(default=0, verbose_name='총 다운로드 수')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
