# Generated by Django 2.1.7 on 2019-03-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeybee_user', '0002_auto_20190330_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='honeybeeuser',
            table='users',
        ),
    ]
