# Generated by Django 2.1.7 on 2019-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeybee_user', '0003_auto_20190330_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='honeybeeuser',
            table='honeybee_user',
        ),
    ]
