# Generated by Django 2.1.7 on 2019-05-04 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import honeybee_user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyBeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('introduce', models.TextField(blank=True, max_length=100)),
                ('total_like', models.IntegerField(default=0)),
                ('total_down', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_address', models.ImageField(upload_to=honeybee_user.models.user_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('share', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honeybee_user.HoneyBeeUser')),
            ],
        ),
    ]
