# Generated by Django 2.1.7 on 2019-05-04 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('honeybee_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeybeeuser',
            name='id',
        ),
        migrations.AddField(
            model_name='honeybeeuser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='pk_id'),
        ),
    ]
