# Generated by Django 2.1.7 on 2019-05-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honeybee_user', '0002_auto_20190504_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
